<?php

/**
 * @file
 * Contains drupal_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupal_test module.
    case 'help.page.drupal_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module for a drupal test.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function drupal_test_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  
  if($form_id == 'drupal_test_config_permutations') {
    // Alter submit button text.
    $form['actions']['submit']['#value'] = t('Save');
  }
}
