<?php

/**
 * @file
 * Contains drupal_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupal_test module.
    case 'help.page.drupal_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module for a drupal test.') . '</p>';
      return $output;

    default:
  }
}
